version: '3.8'

services:
  cae-server:
    build:
      context: .
    container_name: cam-server
    restart: always
    ports:
      - 4000:4000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
